-- Problem Statement : https://www.hackerrank.com/challenges/harry-potter-and-wands/problem

SELECT ID,AGE,m.COINS_NEEDED,m.POWER FROM 
(SELECT CODE,POWER,MIN(COINS_NEEDED) AS COINS_NEEDED FROM WANDS GROUP BY CODE,POWER) AS m 
JOIN WANDS AS w ON m.CODE=w.CODE AND m.COINS_NEEDED=w.COINS_NEEDED AND m.POWER = w.POWER JOIN WANDS_PROPERTY AS p ON p.CODE=m.CODE 
WHERE p.IS_EVIL=0 ORDER BY m.POWER DESC,AGE DESC;
