-- Problem Statement : https://www.hackerrank.com/challenges/full-score/problem

SELECT h.HACKER_ID,h.NAME 
  FROM SUBMISSIONS AS s JOIN HACKERS AS h 
  ON s.HACKER_ID = h.HACKER_ID JOIN CHALLENGES AS c 
  ON c.CHALLENGE_ID = s.CHALLENGE_ID JOIN DIFFICULTY AS d 
  ON d.DIFFICULTY_LEVEL=c.DIFFICULTY_LEVEL 
    WHERE (d.SCORE = s.SCORE) 
    GROUP BY h.HACKER_ID,h.NAME HAVING COUNT(*)>1 
    ORDER BY COUNT(*) DESC, h.HACKER_ID;
